### ISSUE TITLE
talk about importing WikiPathways via the RDF export

### ISSUE THREAD

**Issue by egonw** [Mathelab/RaMP-DB#1]
Advantages:

- has normalized metabolite IDs
- has ontology tagging (e.g. Pathway Ontology)
- normalized various types of interactions

cc @DeniseSl22

**Comment by DeniseSl22** [comment]
And, there is a monthly release, which is being supported by the latest version of our mapping tool (BridgeDb), which gives you the newest insights possible. And there is an API (with various examples):
https://www.wikipathways.org/index.php/Help:WikiPathways_Webservice/API

**Comment by Mathelab** [comment]
Thanks Egon,

We’ll look into this after the resubmission and start on it right…

Ewy

**Comment by ewymathe** [comment]
Thanks for the link Denise!

**Comment by ewymathe** [comment]
Denise and Egon,

We're finally looking into importing RDF files from WP and are seeing that indeed, many more ids for metabolites are linked in those files (relative to the GPML).  

Looking at the rdf files though, we have a few questions:
1) In the WP661.tti file, we're noticing some entries have
`a                   wp:DataNode , wp:Metabolite ;`
while others have 
`a                   wp:Metabolite , wp:DataNode ;`

Could you explain why that is?

Also, we are hoping to download the interactions so we know what genes are catalyzing/inhibiting which compounds.  Should we also be using these RDF files?  We've noticed that some of the interactions are between a compound and another compound, a compound and a gene, or a compound and a pathway.  What exactly does an interaction between a compound and a compound or a compound and a pathway mean?  Also, how can we get the information about whether an enzyme is catalyzing or inhibiting a reaction?

If you prefer that I post this on somewhere more relevant, just let me know.

Best,
Ewy

**Comment by egonw** [comment]
Dear Ewy, Denise just pointed me to your message... I had missed it... looking at the date, I guess this was just after the Winterschool...

About the order of wp:DataNode and wp:Metabolite... in Turtle, the order does not mention, as both are equivalent; that is, they define the same triples... the line basically says that the subject both a DataNode and a Metabolite is ('a' == rdf:type).

My recommendation would be to use SPARQL to extract data from the RDF (that's what I do). The result would be a simple table. 

That you can indeed use to find the genes (proteins) catalyzing/inhibiting compounds too. The interactions in pathways are indeed very diverse in nature... that's just how biology is and biologists are. The interaction is an overarching concept, and includes things a chemist would not call an interaction, like a metabolic conversion, and those too are modeled in WikiPathways as an interaction. The other combinations can have varying meaning. We've recently been working on looking into these... btw, keep in mind that in pathways, biologists use gene IDs often where proteins are doing the real work... so, an example of a biologically valid gene<>compound interaction (conversion even) would be insulin... insulin you will find in metabolite databases (e.g. ChEBI, as a large peptide), but clearly is a breakdown of a protein encoded by a gene.

For the exact info of what the interaction is, MIM types exist... e.g. see [this article](https://academic.oup.com/bioinformatics/article/27/15/2165/402836)... but we have a long way to go there... that needs a project to get fully right... now we do bits here and there are part of curation events...
