### ISSUE TITLE
Case sensitive Table's name

### ISSUE THREAD

**Issue by sophielem** [Mathelab/RaMP-DB#15]
In Unix/linux environment, the function rampFindSynonymFromSynonym listed in rampQueryHelper.R file meets an error. In fact, the table’s name used is ‘analyteSynonym’ while the table’s name in the database is ‘analytesynonym’. The function meets a case sensitive problem. 

one among other faulty lines : 
https://github.com/Mathelab/RaMP-DB/blob/01caa3c5a8dbed8ed981cd3c74421c295136cb0d/R/rampQueryHelper.R#L42

**Comment by bofei5675** [comment]
Fixed! Thanks for your comments!
