### ISSUE TITLE
can not install rmysql

### ISSUE THREAD

**Issue by FADHLyemen** [Mathelab/RaMP-DB#16]
I try to install rmysql but could not, do you have any suggestions?
https://stackoverflow.com/questions/24537257/installing-rmysql-in-mavericks

**Comment by FADHLyemen** [comment]
This solve it, thank you
sudo apt-get install libmysql++-dev
https://stackoverflow.com/questions/24788670/error-installing-rmysql-mysql-5-5-37-in-ubuntu-14-04

**Comment by Mathelab** [comment]
Good to hear!  Let us know if you run into any other issues.
Best,
Ewy
