### ISSUE TITLE
Difficulty installing the RaMP R package in R version 4.0

### ISSUE THREAD

**Issue by billy-s-lab** [Mathelab/RaMP-DB#33]
Hello, 

I recently upgraded to R version 4.0.0. I am trying to reinstall the RaMP R package on my system but getting the following error:

devtools::install_github("mathelab/RAMP-DB", force = TRUE)

Downloading GitHub repo mathelab/RAMP-DB@master
✓  checking for file ‘/private/var/folders/s6/smq8l3gx6dvb78q6c47kxz480000gn/T/RtmpWCklX4/remotes48c52b79554d/Mathelab-RaMP-DB-3a96ed8/DESCRIPTION’ (371ms)
─  preparing ‘RaMP’:
✓  checking DESCRIPTION meta-information ...
   Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
     PCRE pattern compilation error
   	'unrecognized character follows \'
   	at 'img/.*$'
   Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
     invalid regular expression '^\img/.*$'
   Execution halted
Error: Failed to install 'RaMP' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr:
E> * checking for file ‘/private/var/folders/s6/smq8l3gx6dvb78q6c47kxz480000gn/T/RtmpWCklX4/remotes48c52b79554d/Mathelab-RaMP-DB-3a96ed8/DESCRIPTION’ ... OK
E> * preparing ‘RaMP’:
E> * checking DESCRIPTION meta-information ... OK
E> Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
E>   PCRE pattern compilation error
E> 	'unrecognized character follows \'
E> 	at 'img/.*$'
E> Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
E>   invalid regular expression '^\img/.*$'
E> Execution halted

Session info:
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_IE.UTF-8/en_IE.UTF-8/en_IE.UTF-8/C/en_IE.UTF-8/en_IE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] IntLIM_0.1.0

Any help greatly appreciated.

**Comment by geoffrosen** [comment]
#35 should fix this

**Comment by fuyaloha** [comment]
Hi, I have the same problem with RaMP installing in R version 4.0. Could you please help? My email: fuy@hawaii.edu
Many thanks in advance,
Yuanyuan

**Comment by Mathelab** [comment]
Please see the following repo for updated changes, including installation instructions for the new version of R:
https://github.com/ncats/RaMP-DB/
The new repo is maintained and updated.  The lag was due to a change in institution.  Thank you for your patience and thank you for your interest.

**Comment by fuyaloha** [comment]
Thank you so much for your reply. I have checked the
https://github.com/ncats/RaMP-DB/
But,  How can I install RAMP?  Could you please help? Many thanks.

Best,
Yuanyuan
