### ISSUE TITLE
Clustering with a small list of metabolites

### ISSUE THREAD

**Issue by andyptt21** [Mathelab/RaMP-DB#5]
Clustering throws an error message if you attempt to cluster with a short list of metabolite pathways (e.g. glucose, cholesterol), and then crashes if you retry clustering

**Comment by Mathelab** [comment]
What error message?

**Comment by andyptt21** [comment]
It's the correct "Use less stringent filters message" you should get when
no pathways are fed into the clustering function, but when you try to
adjust filters to address the issue the app crashes. It's a problem with my
code, just leaving a note so I can look at it later.

-Andy
