### ISSUE TITLE
Network visualization not working in app

### ISSUE THREAD

**Issue by andyptt21** [Mathelab/RaMP-DB#6]
Tried to make networks with "Glucose" in individual metabolite input and "Glucose" and "Cholesterol" in batch input for tab 4. Got the same error in both instances:

Warning: Error in %>%: could not find function "%>%"                                           
                                                                                                           | Stack trace (innermost first):                                                                 
                                                                                                           |     80: RaMP::plotCataNetwork                                                                  
                                                                                                           |     79: func [server/tab4.R#135]                                                               
                                                                                                           |     78: origRenderFunc                                                                         
                                                                                                           |     77: output$networkmulti                                                                    
                                                                                                           |      2: shiny::runApp                                                                          
                                                                                                           |      1: runRaMPapp

**Comment by Mathelab** [comment]
library(magrittr)
libraries are not being loaded properly….
Then rerun app…

**Comment by ewymathe** [comment]
Fixed. Please close.
