### ISSUE TITLE
Prepend ID type to ids

### ISSUE THREAD

**Issue by ewymathe** [Mathelab/RaMP-DB#7]
All id types should be prepended to all compound and gene ids.

Here are the id types currently in RaMP:
mysql> select distinct(IDtype) from source where geneOrCompound ="compound";
+------------+
| IDtype     |
+------------+
| kegg       |
| CAS        |
| chebi      |
| chemspider |
| hmdb       |
| LIPIDMAPS  |
| pubchem    |
+------------+
7 rows in set (0.14 sec)

mysql> select distinct(IDtype) from source where geneOrCompound ="gene";
+--------------------+
| IDtype             |
+--------------------+
| enzymeNomenclature |
| kegg               |
| uniprot            |
| ensembl            |
| entrez             |
| hmdb               |
+--------------------+
6 rows in set (0.08 sec)

**Comment by bofei5675** [comment]
ID types are prepended to the source ID since 3/1/2018
